// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://majpyfbfxjbrdpznpdur.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1hanB5ZmJmeGpicmRwem5wZHVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1OTA2MTMsImV4cCI6MjA3MTE2NjYxM30.1izXSd8GPRDeFaTfJl5Teez4CV98NYLqSeDLViuUkxA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});